name: flake8

on:
  push:

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 2.7
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Flake8
        run: |
          pip install flake8
          flake8 --max-line-length=100 guardduty/
